//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CORNBusinessLayer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=SAMS_DB_FG_Lahore;Persist Security Info=True;User I" +
            "D=sa;Password=sa")]
        public string SAMS_DB_FG_LahoreConnectionString {
            get {
                return ((string)(this["SAMS_DB_FG_LahoreConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=SAMS_SERVER_FG;Persist Security Info=True;User ID=s" +
            "a;Password=sa")]
        public string SAMS_SERVER_FGConnectionString {
            get {
                return ((string)(this["SAMS_SERVER_FGConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=SAMS_ONLINE_FDM;Persist Security Info=True;User ID=" +
            "sa;Password=sa")]
        public string SAMS_ONLINE_FDMConnectionString {
            get {
                return ((string)(this["SAMS_ONLINE_FDMConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=SAMS_ONLINE_FDM_Current;Persist Security Info=True;" +
            "User ID=sa;Password=sa")]
        public string SAMS_ONLINE_FDM_CurrentConnectionString {
            get {
                return ((string)(this["SAMS_ONLINE_FDM_CurrentConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=SAMS_ONLINE_FDM_TEST;Persist Security Info=True;Use" +
            "r ID=sa;Password=sa")]
        public string SAMS_ONLINE_FDM_TESTConnectionString {
            get {
                return ((string)(this["SAMS_ONLINE_FDM_TESTConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=SAMS_ONLINE_FDM_New;Persist Security Info=True;User" +
            " ID=sa;Password=sa")]
        public string SAMS_ONLINE_FDM_NewConnectionString {
            get {
                return ((string)(this["SAMS_ONLINE_FDM_NewConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=SAMS_ONLINE_FDM_BDN;User ID=sa;Password=123")]
        public string SAMS_ONLINE_FDM_BDNConnectionString {
            get {
                return ((string)(this["SAMS_ONLINE_FDM_BDNConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=SAMS_ONLINE_BDN;Persist Security Info=True;User ID=" +
            "sa;Password=sa")]
        public string SAMS_ONLINE_BDNConnectionString {
            get {
                return ((string)(this["SAMS_ONLINE_BDNConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=SAMS_ONLINE_SGA;Persist Security Info=True;User ID=" +
            "sa;Password=sa")]
        public string SAMS_ONLINE_SGAConnectionString {
            get {
                return ((string)(this["SAMS_ONLINE_SGAConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=SAMS_ONLINE_FDMPL;Integrated Security=True")]
        public string SAMS_ONLINE_FDMPLConnectionString {
            get {
                return ((string)(this["SAMS_ONLINE_FDMPLConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ALI-PC;Initial Catalog=SAMS_ONLINE_FDMPL;Persist Security Info=True;U" +
            "ser ID=sa")]
        public string SAMS_ONLINE_FDMPLConnectionString1 {
            get {
                return ((string)(this["SAMS_ONLINE_FDMPLConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=ArshadPOS;Persist Security Info=True;User ID=sa")]
        public string SAMS_ONLINE_FDMPLConnectionString2 {
            get {
                return ((string)(this["SAMS_ONLINE_FDMPLConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=FS-DEV-II;Initial Catalog=need;Integrated Security=True")]
        public string needConnectionString {
            get {
                return ((string)(this["needConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=fs-l3\\FASTSERVICES;Initial Catalog=dbASons;Integrated Security=True")]
        public string dbASonsConnectionString {
            get {
                return ((string)(this["dbASonsConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=tcp:fs-l3\\FASTSERVICES,49172;Initial Catalog=dbMaleeBO;User ID=Ali;Pa" +
            "ssword=ali1234")]
        public string dbMaleeBOConnectionString {
            get {
                return ((string)(this["dbMaleeBOConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=tcp:fs-l3\\FASTSERVICES,49172;Initial Catalog=dbTLlive;User ID=Ali;Pas" +
            "sword=ali1234")]
        public string dbTLliveConnectionString {
            get {
                return ((string)(this["dbTLliveConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=tcp:fs-l3\\FASTSERVICES,49172;Initial Catalog=dbAutumTest;Persist Secu" +
            "rity Info=True;User ID=Ali;Password=ali1234")]
        public string dbAutumTestConnectionString {
            get {
                return ((string)(this["dbAutumTestConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.18.221;Initial Catalog=dbCafe;User ID=sa;Password=fast1234")]
        public string dbCafeConnectionString {
            get {
                return ((string)(this["dbCafeConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=FS-DEV-I5\\MSSQLSERVER2012;Initial Catalog=dbNewCafe;Integrated Securi" +
            "ty=True;User ID=sa;Password=firms1234;Connect Timeout=0")]
        public string dbNewCafeConnectionString {
            get {
                return ((string)(this["dbNewCafeConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=Mozzarella2720170310;Integrated Security=True")]
        public string Mozzarella2720170310ConnectionString {
            get {
                return ((string)(this["Mozzarella2720170310ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=FS-Dev-R1;Initial Catalog=Mozzarella2720170310;User ID=sa;Password=fi" +
            "rms1234")]
        public string Mozzarella2720170310ConnectionString1 {
            get {
                return ((string)(this["Mozzarella2720170310ConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=FS-Dev-R1;Initial Catalog=dbNewBuild;Persist Security Info=True;User " +
            "ID=sa;Password=firms1234")]
        public string dbNewBuildConnectionString {
            get {
                return ((string)(this["dbNewBuildConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=FS-DEV-SADAQAT;Initial Catalog=dbCORNPOs;User ID=sa;Password=Fast1234" +
            "")]
        public string dbCORNPOsConnectionString {
            get {
                return ((string)(this["dbCORNPOsConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=FS-DEV-SADAQAT;Initial Catalog=dbCORNPOs;Integrated Security=True")]
        public string dbCORNPOsConnectionString1 {
            get {
                return ((string)(this["dbCORNPOsConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=FS-DEV-R1;Initial Catalog=Cafe-Malee;Persist Security Info=True;User " +
            "ID=sa;Password=firms1234")]
        public string Cafe_MaleeConnectionString {
            get {
                return ((string)(this["Cafe_MaleeConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=Ali-PC;Initial Catalog=Signature;User ID=sa;Password=Fast1234")]
        public string SignatureConnectionString {
            get {
                return ((string)(this["SignatureConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=corn.faastdemo.com;Initial Catalog=Terrazza;User ID=sa;Password=Fast1" +
            "234")]
        public string TerrazzaConnectionString {
            get {
                return ((string)(this["TerrazzaConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=localhost;Initial Catalog=DemoCafe;Persist Security Info=True;User ID" +
            "=sa;Password=Fast1234")]
        public string DemoCafeConnectionString {
            get {
                return ((string)(this["DemoCafeConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=65.1.163.122;Initial Catalog=DemoCafe;User ID=app;Password=Fast123412" +
            "34")]
        public string DemoCafeConnectionString1 {
            get {
                return ((string)(this["DemoCafeConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-GQFFB0O\\SQLEXPRESS;Initial Catalog=dbDevCafe;Integrated Secur" +
            "ity=True")]
        public string dbDevCafeConnectionString {
            get {
                return ((string)(this["dbDevCafeConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-Q07NSGI\\SQLEXPRESS;Initial Catalog=VillaBroadway;Integrated S" +
            "ecurity=True")]
        public string VillaBroadwayConnectionString {
            get {
                return ((string)(this["VillaBroadwayConnectionString"]));
            }
        }
    }
}
